version: 2

defaults: &defaults
  working_directory: ~/react-ui-components
  docker:
    - image: circleci/node:dubnium

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - dependency-cache-{{ checksum "package.json" }}-
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check linters
          command: yarn lint

  bundlewatch:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build packages
          command: yarn build-prod
      - run:
          name: Remove non-shipped files
          command: ./.bundlewatch/remove-non-watched-files.sh
      - run:
          name: Run BundleWatch
          command: yarn bundlewatch

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Copy/Upload Results
          command: |
            mkdir -p ./test-results/mocha
            [[ -e ./test-results.xml ]] && cp ./test-results.xml ./test-results/mocha/test-results.xml
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: test-results

  maybe_deploy:
    # Tag filtering in CircleCI is unreliable - this is hacky, but it works
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Maybe Deploy
          command: |
            # deploy tagged commits only
            if ! git describe --exact-match HEAD > /dev/null 2>&1; then echo "Not on tagged commit - nothing to do"; exit 0; fi
            echo "TODO: npm publish"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - bundlewatch:
          requires:
            - setup
      - maybe_deploy:
          requires:
            - lint
            - test
            - bundlewatch
